# Two pods, one container each
# Each container asking for 1 distinct CPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: cpu-test1

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: cpu-test1
  name: cpu.example.com
spec:
  spec:
    resourceClassName: cpu.example.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: cpu-test1
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: cpu
  resourceClaims:
  - name: cpu
    source:
      resourceClaimTemplateName: cpu.example.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: cpu-test1
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: cpu
  resourceClaims:
  - name: cpu
    source:
      resourceClaimTemplateName: cpu.example.com
