/*
 * Copyright 2023 The Kubernetes Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubernetes-sigs/dra-example-driver/api/example.com/resource/cpu/v1alpha1"
	scheme "github.com/kubernetes-sigs/dra-example-driver/pkg/example.com/resource/cpu/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CpuClaimParametersesGetter has a method to return a CpuClaimParametersInterface.
// A group's client should implement this interface.
type CpuClaimParametersesGetter interface {
	CpuClaimParameterses(namespace string) CpuClaimParametersInterface
}

// CpuClaimParametersInterface has methods to work with CpuClaimParameters resources.
type CpuClaimParametersInterface interface {
	Create(ctx context.Context, cpuClaimParameters *v1alpha1.CpuClaimParameters, opts v1.CreateOptions) (*v1alpha1.CpuClaimParameters, error)
	Update(ctx context.Context, cpuClaimParameters *v1alpha1.CpuClaimParameters, opts v1.UpdateOptions) (*v1alpha1.CpuClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CpuClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CpuClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CpuClaimParameters, err error)
	CpuClaimParametersExpansion
}

// cpuClaimParameterses implements CpuClaimParametersInterface
type cpuClaimParameterses struct {
	client rest.Interface
	ns     string
}

// newCpuClaimParameterses returns a CpuClaimParameterses
func newCpuClaimParameterses(c *CpuV1alpha1Client, namespace string) *cpuClaimParameterses {
	return &cpuClaimParameterses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cpuClaimParameters, and returns the corresponding cpuClaimParameters object, and an error if there is any.
func (c *cpuClaimParameterses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CpuClaimParameters, err error) {
	result = &v1alpha1.CpuClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CpuClaimParameterses that match those selectors.
func (c *cpuClaimParameterses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CpuClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CpuClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cpuClaimParameterses.
func (c *cpuClaimParameterses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cpuClaimParameters and creates it.  Returns the server's representation of the cpuClaimParameters, and an error, if there is any.
func (c *cpuClaimParameterses) Create(ctx context.Context, cpuClaimParameters *v1alpha1.CpuClaimParameters, opts v1.CreateOptions) (result *v1alpha1.CpuClaimParameters, err error) {
	result = &v1alpha1.CpuClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cpuClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cpuClaimParameters and updates it. Returns the server's representation of the cpuClaimParameters, and an error, if there is any.
func (c *cpuClaimParameterses) Update(ctx context.Context, cpuClaimParameters *v1alpha1.CpuClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.CpuClaimParameters, err error) {
	result = &v1alpha1.CpuClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		Name(cpuClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cpuClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cpuClaimParameters and deletes it. Returns an error if one occurs.
func (c *cpuClaimParameterses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cpuClaimParameterses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cpuClaimParameters.
func (c *cpuClaimParameterses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CpuClaimParameters, err error) {
	result = &v1alpha1.CpuClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cpuclaimparameterses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
