/*
 * Copyright 2023 The Kubernetes Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubernetes-sigs/dra-example-driver/api/example.com/resource/cpu/v1alpha1"
	scheme "github.com/kubernetes-sigs/dra-example-driver/pkg/example.com/resource/cpu/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CpuResourceClassParametersGetter has a method to return a CpuResourceClassParametersInterface.
// A group's client should implement this interface.
type CpuResourceClassParametersGetter interface {
	CpuResourceClassParameters() CpuResourceClassParametersInterface
}

// CpuResourceClassParametersInterface has methods to work with CpuResourceClassParameters resources.
type CpuResourceClassParametersInterface interface {
	Create(ctx context.Context, cpuResourceClassParameters *v1alpha1.CpuResourceClassParameters, opts v1.CreateOptions) (*v1alpha1.CpuResourceClassParameters, error)
	Update(ctx context.Context, cpuResourceClassParameters *v1alpha1.CpuResourceClassParameters, opts v1.UpdateOptions) (*v1alpha1.CpuResourceClassParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CpuResourceClassParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CpuResourceClassParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CpuResourceClassParameters, err error)
	CpuResourceClassParametersExpansion
}

// cpuResourceClassParameters implements CpuResourceClassParametersInterface
type cpuResourceClassParameters struct {
	client rest.Interface
}

// newCpuResourceClassParameters returns a CpuResourceClassParameters
func newCpuResourceClassParameters(c *CpuV1alpha1Client) *cpuResourceClassParameters {
	return &cpuResourceClassParameters{
		client: c.RESTClient(),
	}
}

// Get takes name of the cpuResourceClassParameters, and returns the corresponding cpuResourceClassParameters object, and an error if there is any.
func (c *cpuResourceClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CpuResourceClassParameters, err error) {
	result = &v1alpha1.CpuResourceClassParameters{}
	err = c.client.Get().
		Resource("cpuresourceclassparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CpuResourceClassParameters that match those selectors.
func (c *cpuResourceClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CpuResourceClassParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CpuResourceClassParametersList{}
	err = c.client.Get().
		Resource("cpuresourceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cpuResourceClassParameters.
func (c *cpuResourceClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("cpuresourceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cpuResourceClassParameters and creates it.  Returns the server's representation of the cpuResourceClassParameters, and an error, if there is any.
func (c *cpuResourceClassParameters) Create(ctx context.Context, cpuResourceClassParameters *v1alpha1.CpuResourceClassParameters, opts v1.CreateOptions) (result *v1alpha1.CpuResourceClassParameters, err error) {
	result = &v1alpha1.CpuResourceClassParameters{}
	err = c.client.Post().
		Resource("cpuresourceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cpuResourceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cpuResourceClassParameters and updates it. Returns the server's representation of the cpuResourceClassParameters, and an error, if there is any.
func (c *cpuResourceClassParameters) Update(ctx context.Context, cpuResourceClassParameters *v1alpha1.CpuResourceClassParameters, opts v1.UpdateOptions) (result *v1alpha1.CpuResourceClassParameters, err error) {
	result = &v1alpha1.CpuResourceClassParameters{}
	err = c.client.Put().
		Resource("cpuresourceclassparameters").
		Name(cpuResourceClassParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cpuResourceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cpuResourceClassParameters and deletes it. Returns an error if one occurs.
func (c *cpuResourceClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("cpuresourceclassparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cpuResourceClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("cpuresourceclassparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cpuResourceClassParameters.
func (c *cpuResourceClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CpuResourceClassParameters, err error) {
	result = &v1alpha1.CpuResourceClassParameters{}
	err = c.client.Patch(pt).
		Resource("cpuresourceclassparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
