//
//Copyright 2023 The Kubernetes Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.5.0
// source: pkg/cpusetupdater/cpusetupdater.proto

package cpusetupdater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpusetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	NodeName     string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *CpusetRequest) Reset() {
	*x = CpusetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpusetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpusetRequest) ProtoMessage() {}

func (x *CpusetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpusetRequest.ProtoReflect.Descriptor instead.
func (*CpusetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cpusetupdater_cpusetupdater_proto_rawDescGZIP(), []int{0}
}

func (x *CpusetRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CpusetRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CpusetRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

type CpusetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpuset string `protobuf:"bytes,1,opt,name=cpuset,proto3" json:"cpuset,omitempty"`
}

func (x *CpusetResponse) Reset() {
	*x = CpusetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpusetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpusetResponse) ProtoMessage() {}

func (x *CpusetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpusetResponse.ProtoReflect.Descriptor instead.
func (*CpusetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cpusetupdater_cpusetupdater_proto_rawDescGZIP(), []int{1}
}

func (x *CpusetResponse) GetCpuset() string {
	if x != nil {
		return x.Cpuset
	}
	return ""
}

var File_pkg_cpusetupdater_cpusetupdater_proto protoreflect.FileDescriptor

var file_pkg_cpusetupdater_cpusetupdater_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x72, 0x2f, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x22, 0x6b, 0x0a, 0x0d, 0x43, 0x70, 0x75, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x70, 0x75, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x32, 0x57, 0x0a,
	0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x50, 0x55, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x63, 0x70, 0x75, 0x73,
	0x65, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x70, 0x75, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x70, 0x75, 0x73, 0x65, 0x74,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x70, 0x75, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d,
	0x73, 0x69, 0x67, 0x73, 0x2f, 0x64, 0x72, 0x61, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x70, 0x75, 0x73,
	0x65, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_cpusetupdater_cpusetupdater_proto_rawDescOnce sync.Once
	file_pkg_cpusetupdater_cpusetupdater_proto_rawDescData = file_pkg_cpusetupdater_cpusetupdater_proto_rawDesc
)

func file_pkg_cpusetupdater_cpusetupdater_proto_rawDescGZIP() []byte {
	file_pkg_cpusetupdater_cpusetupdater_proto_rawDescOnce.Do(func() {
		file_pkg_cpusetupdater_cpusetupdater_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_cpusetupdater_cpusetupdater_proto_rawDescData)
	})
	return file_pkg_cpusetupdater_cpusetupdater_proto_rawDescData
}

var file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_cpusetupdater_cpusetupdater_proto_goTypes = []interface{}{
	(*CpusetRequest)(nil),  // 0: cpusetupdater.CpusetRequest
	(*CpusetResponse)(nil), // 1: cpusetupdater.CpusetResponse
}
var file_pkg_cpusetupdater_cpusetupdater_proto_depIdxs = []int32{
	0, // 0: cpusetupdater.Allocate.UpdateCPUSet:input_type -> cpusetupdater.CpusetRequest
	1, // 1: cpusetupdater.Allocate.UpdateCPUSet:output_type -> cpusetupdater.CpusetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_cpusetupdater_cpusetupdater_proto_init() }
func file_pkg_cpusetupdater_cpusetupdater_proto_init() {
	if File_pkg_cpusetupdater_cpusetupdater_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpusetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpusetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_cpusetupdater_cpusetupdater_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cpusetupdater_cpusetupdater_proto_goTypes,
		DependencyIndexes: file_pkg_cpusetupdater_cpusetupdater_proto_depIdxs,
		MessageInfos:      file_pkg_cpusetupdater_cpusetupdater_proto_msgTypes,
	}.Build()
	File_pkg_cpusetupdater_cpusetupdater_proto = out.File
	file_pkg_cpusetupdater_cpusetupdater_proto_rawDesc = nil
	file_pkg_cpusetupdater_cpusetupdater_proto_goTypes = nil
	file_pkg_cpusetupdater_cpusetupdater_proto_depIdxs = nil
}
